(defun tree-generator (n level)
	(cond 
		((<= n 0) nil)
		((= n 1) (list (+ level 1)))
		(t ((lambda (x tree-level) 
				(cons tree-level (append(list (tree-generator x tree-level)) 
										(list (tree-generator (- (- n 1) x) tree-level))))
			) (random n) (+ level 1) 
		))
	)
)

(defun result-tree (n) 
	(tree-generator n 0)
) 